### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by linkmauve**
Surprisingly, none of them required any code change.

### CODE REVIEW

**Comment by kraag-gorim** [comment]
I think the `^` notation should be kept.

**Comment by linkmauve** [comment]
No, see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

More specifically, “The string "0.1.12" is a semver version requirement. Since this string does not have any operators in it, it is interpreted the same way as if we had specified "^0.1.12", which is called a caret requirement.”

**Comment by kraag-gorim** [comment]
Yeah I looked it up. I still don't get, why you removed it.

**Comment by linkmauve** [comment]
Mostly just for consistency with the other dependencies, which already didn’t have it.

**Comment by sseemayer** [comment]
Thanks a lot for this!

**Pull request merged**
