### PR TITLE
Add support for native group order

### LINKED ISSUE #28: Preserve order (BTreeMap?)
The order is lost on groups when iterating.

**Disclaimer**: I've not looked at the internals of this crate nor the keepass format.

Assuming this crate reads everything in order from the .kdbx file, a `BTreeMap` would retain said order. If not, perhaps there is an order index somewhere on each group which could help?

### PR DESCRIPTION
**Pull request by leaty**
Fixes #28 

I made use of the crate [indexmap](https://github.com/bluss/indexmap) to retain the original insert order of groups found in the kdbx file. This means that iterating over `child_groups` is sorted just like the original file (and is identical to how it looks in keepass frontends). I've not tested this in anything but a 4.0 kdbx file however, but as long as they're read and inserted in the same order, other versions should work identically. 

Note: This does not automatically make `NodeIter` sort perfectly, but doing a `self.queue.remove` of the first element instead of `self.queue.pop` works. I did not include it though, as I'm not sure if something like that is wanted - I don't personally use it as I need a more true recurse to retain parent/child relationships.

Note 2: I chose to exclude entries from this change, as I do not know if entries are supposed to have a native order. In the frontend that I use - `keepassxc`, you're always forced to sort entries by something (there is no manual index order).

Thanks a lot for this crate, it helped me to write a persistent keepass backend (shameless plug: [rkeep](https://github.com/leaty/rkeep)) for [rofi](https://github.com/davatorium/rofi).

Let me know if something should be changed!

### CODE REVIEW

**Comment by sseemayer** [comment]
Thanks a lot for the PR, and for the explanation! I read the code first and had exactly the two questions that you already wrote notes for 😆 

If you don't mind, could you also make the proposed modification on the `NodeIter`? For people using the library, I think it would be less confusing if both ways of accessing yield the expected order of groups.

**Comment by leaty** [comment]
No probs! I'll do that later today.

I had a thought about entries, do you think it'd be worth storing them in a BTreeMap? That way the entries are at the very least sorted consistently (alphabetically), so that each run has perfectly consistent iterations. You could still sort them as you please, but at least it''s a sane default.

**Comment by sseemayer** [comment]
BTreeMap sounds good :) I expect most people will want alphabetic sorting regardless.

FYI, I also still have #24 on my to-do list, so I am planning to touch your changes again right after your MR is merged to fix this issue, then release a new crate version.

**Comment by leaty** [comment]
I'll make a new PR with those added changes.

**Pull request closed without merging**
